[app]
sock_tcp = "tcp://127.0.0.1:27219"

[forge]
pub_sub_key = "forgetothemoon!"

[tendermint.genesis]
genesis_time = "2019-02-10T19:22:08.938749Z"
max_bytes = 600000

### begin validators
[[tendermint.genesis.validators]]
### end validators
